services:
  mobile_base:
    image: mobile_base:release

    container_name: mobile_base
    runtime: nvidia
    network_mode: host
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - TOPIC_NAMESPACE=${TOPIC_NAMESPACE:-}
      - MOBILE_BASE_INFLUXDB_TOKEN=${MOBILE_BASE_INFLUXDB_TOKEN:-}

    volumes:
      - ./maps:/workspaces/mobile_base/maps
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0

    working_dir: /workspaces/mobile_base

    stdin_open: true
    tty: true

    command: sleep infinity
