[SERVICE]
    Flush             1
    Log_Level         info

[INPUT]
    Name              tail
    Tag               ros.launch
    Path              /root/.ros/log/*/launch.log
    Read_from_Head    false
    Refresh_Interval  1
    storage.type      memrb
    Mem_Buf_Limit     32M

[FILTER]
    Name              record_modifier
    Match             ros.launch
    Record            robot_id ${MOBILE_BASE_ROBOT_ID}
    Record            source ros_launch_log

[OUTPUT]
    Name              opensearch
    Match             ros.launch
    Host              ${MOBILE_BASE_OPENSEARCH_HOST}
    Port              ${MOBILE_BASE_OPENSEARCH_PORT}
    TLS               ${MOBILE_BASE_OPENSEARCH_TLS}
    HTTP_User         ${MOBILE_BASE_OPENSEARCH_USERNAME}
    HTTP_Passwd       ${MOBILE_BASE_OPENSEARCH_PASSWORD}
    Logstash_Format   On
    Logstash_Prefix   mobile-base-logs
    Suppress_Type_Name On
    Retry_Limit       2
